const users = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        gender: 'Male',
        deductions: "",
        email: "john.doe@example.com",
        role: "Software Engineer",
        startDate: "2023-05-10",
        monthlyGross: "₦500,000",
        department: "Engineering",
        netSalary: "₦450,000",
        phoneNumber: "08012345678",
        bank: 'Access Bank',
        accountNumber: '0123456278'
    },
    {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        gender: 'Female',
        deductions: "",
        email: "jane.smith@example.com",
        role: "Product Manager",
        startDate: "2022-08-15",
        monthlyGross: "₦600,000",
        department: "Product",
        netSalary: "₦550,000",
        phoneNumber: "08098765432",
        bank: 'UBA',
        accountNumber: '0123456278'
    },
    {
        id: 3,
        firstName: "David",
        lastName: "Johnson",
        gender: 'Male',
        deductions: "",
        email: "david.johnson@example.com",
        role: "UX Designer",
        startDate: "2021-11-20",
        monthlyGross: "₦450,000",
        department: "Design",
        netSalary: "₦400,000",
        phoneNumber: "08023456789",
        bank: 'Sterling Bank',
        accountNumber: '0123456278'
    },
    {
        id: 4,
        firstName: "Emily",
        lastName: "Brown",
        gender: 'Female',
        deductions: "",
        email: "emily.brown@example.com",
        role: "Marketing Specialist",
        startDate: "2023-02-05",
        monthlyGross: "₦480,000",
        department: "Marketing",
        netSalary: "₦430,000",
        phoneNumber: "08034567890",
        bank: 'FCMB',
        accountNumber: '0123456278'
    },
    {
        id: 5,
        firstName: "Michael",
        lastName: "Williams",
        gender: 'Male',
        deductions: "",
        email: "michael.williams@example.com",
        role: "HR Manager",
        startDate: "2020-06-18",
        monthlyGross: "₦550,000",
        department: "Human Resources",
        netSalary: "₦500,000",
        phoneNumber: "08045678901",
        bank: 'GTB',
        accountNumber: '0123456278'
    }
];

export default users;
