import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppinsRegular = localFont({
  src: "../public/fonts/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  style: "normal",
});

const poppinsBold = localFont({
  src: "../public/fonts/Poppins-Bold.ttf",
  variable: "--font-poppins-bold",
  style: "normal",
});

const poppinsMedium = localFont({
  src: "../public/fonts/Poppins-Medium.ttf",
  variable: "--font-poppins-medium",
  style: "normal",
});

const poppinsSemiBold = localFont({
  src: "../public/fonts/Poppins-SemiBold.ttf",
  variable: "--font-poppins-semibold",
  style: "normal",
});

const poppinsLight = localFont({
  src: "../public/fonts/Poppins-Light.ttf",
  variable: "--font-poppins-light",
  style: "normal",
});

const poppinsExtraBold = localFont({
  src: "../public/fonts/Poppins-ExtraBold.ttf",
  variable: "--font-poppins-extraBold",
  style: "normal",
});

const poppinsBoldItalic = localFont({
  src: "../public/fonts/Poppins-BoldItalic.ttf",
  variable: "--font-poppins-bolditalic",
  style: "normal",
});



export const metadata: Metadata = {
  title: "CredPay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsRegular.variable} 
        ${poppinsMedium.variable} 
        ${poppinsSemiBold.variable} 
        ${poppinsLight.variable} 
        ${poppinsBold.variable}  
        ${poppinsExtraBold.variable}
        ${poppinsBoldItalic.variable}
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
